// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lakmssgxezvhdhmpxdnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxha21zc2d4ZXp2aGRobXB4ZG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTA0MzksImV4cCI6MjA3MTAyNjQzOX0.SCHZ7hg5d_yc058mtpatX9hi3WKJp2s8-Nkbh5JebJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});